name: Data Updater
on:
  schedule:
    - cron:  '20 11 * * *'
  repository_dispatch:
    types: [update_data]

jobs:
  dev-update:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout covid19
      uses: actions/checkout@v2
      with:
        ref: 'development'

    - name: Checkout covid19-scraping
      uses: actions/checkout@v2
      with:
        repository: stop-covid19-hyogo/covid19-scraping
        ref: 'gh-pages'
        path: 'covid19-scraping'

    - name: copy files
      run: |
        cp -p covid19-scraping/*.json data
        rm -f data/open_data_warnings.json
        rm -rf covid19-scraping

    - run: git diff

    - name: Commit files
      continue-on-error: true
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data
        git commit -m "update json data `date '+%Y-%m-%dT%H:%M:%SZ'`"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: ${{ format('Update json data {0}', github.event.head_commit.timestamp) }}
        labels: auto_merge
        branch-suffix: 'short-commit-hash'

  stg-update:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout covid19
        uses: actions/checkout@v2
        with:
          ref: 'staging'

      - name: Checkout covid19-scraping
        uses: actions/checkout@v2
        with:
          repository: stop-covid19-hyogo/covid19-scraping
          ref: 'gh-pages'
          path: 'covid19-scraping'

      - name: copy files
        run: |
          cp -p covid19-scraping/*.json data
          rm -f data/open_data_warnings.json
          rm -rf covid19-scraping

      - run: git diff

      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data
          git commit -m "update json data `date '+%Y-%m-%dT%H:%M:%SZ'`"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ format('Update json data {0}', github.event.head_commit.timestamp) }}
          labels: auto_merge
          branch-suffix: 'short-commit-hash'

  prod-update:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout covid19
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Checkout covid19-scraping
        uses: actions/checkout@v2
        with:
          repository: stop-covid19-hyogo/covid19-scraping
          ref: 'gh-pages'
          path: 'covid19-scraping'

      - name: copy files
        run: |
          cp -p covid19-scraping/*.json data
          rm -f data/open_data_warnings.json
          rm -rf covid19-scraping

      - run: git diff

      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data
          git commit -m "update json data `date '+%Y-%m-%dT%H:%M:%SZ'`"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ format('Update json data {0}', github.event.head_commit.timestamp) }}
          labels: auto_merge
          branch-suffix: 'short-commit-hash'
