name: OGP Builder

on:
  push:
    branches:
      - master
      - staging

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout development
      uses: actions/checkout@v2
    - run: pip3 install selenium
    - run: python3 ./ui-test/ogp_screenshot.py
      env:
        TZ: Asia/Tokyo
    - name: Upload screenshot
      uses: actions/upload-artifact@v1
      with:
        name: ogp
        path: ogp
  upload-stg:
    if: github.ref == 'refs/heads/staging'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout stg-pages
      uses: actions/checkout@v2
      with:
        ref: stg-pages
    - name: Download screenshot
      uses: actions/download-artifact@v1
      with:
        name: ogp
        path: ogp
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ogp
        git commit -m "Update OGP images"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: stg-pages

  upload-prod:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout prod-pages
        uses: actions/checkout@v2
        with:
          ref: prod-pages
      - name: Download screenshot
        uses: actions/download-artifact@v1
        with:
          name: ogp
          path: ogp
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ogp
          git commit -m "Update OGP images"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: prod-pages
